### PR TITLE
Maplist

### PR DESCRIPTION
**Pull request by vicomte**
- Allow more than 100 maps in maplist. (256 for now?)
- Remove the lmctf maps from the maplist menus since they are already present in the LMCTF sets.
- Add menus for the higher lmctf maps (duplicated existing for now, lets clean this up)
- Sort the maplist by name
- (future) randomize the next map selection in pub mode with map throttling based on min/max players on the server and defined min/max in the maplist

### CODE REVIEW

**Review by QwazyWabbitWOS — COMMENTED** [review]
Since maplist menus are arbitrarily limited to 10 lines of map names, why not choose a multiple of 10 rather than multiple of two? 300? What about adding a <next page> to the bottom of group 1, 2, 3... menus so you don't have to reset and recall? I definitely like seeing a sorted maplist.

**Review by QwazyWabbitWOS — COMMENTED** [review]
if (!filee

Line 359, g_save.c looks like a typo. Does this even compile?

**Review by QwazyWabbitWOS — COMMENTED** [review]
Why are you removing -O3? That level of optimization has not been an issue since about gcc 6.x or so. Was this change unintentional?

**Comment by vicomte** [comment]
Lol, sorry, didn't intend to deluge with notices. I'll check your suggestions and take it out of a pr until I have something more complete.

**Pull request closed without merging**
